# Generated by Django 5.0.6 on 2024-07-02 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateOfBirth', models.DateField()),
                ('dzongkhag', models.CharField(max_length=20)),
                ('player_img', models.ImageField(upload_to='player_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('play_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_ground', to='api.ground')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='api.season')),
            ],
        ),
        migrations.CreateModel(
            name='GroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_img', models.ImageField(upload_to='ground_img')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_ground', to='api.ground')),
            ],
        ),
        migrations.CreateModel(
            name='PlayMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('homeScore', models.IntegerField(default=0)),
                ('awayScore', models.IntegerField(default=0)),
                ('fixture', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fixture', to='api.fixture')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTeam', models.BooleanField(default=True)),
                ('eventType', models.CharField(choices=[('G', 'Goal'), ('I', 'Injured'), ('Y', 'Yellow Card'), ('R', 'Red Card'), ('S', 'Substitution'), ('F', 'Foul'), ('O', 'Offside'), ('C', 'Corner'), ('FK', 'Free Kick'), ('SG', 'Self Goal / Own Goal'), ('A', 'Assists'), ('P', 'Penalty')], max_length=2)),
                ('event_minute', models.PositiveIntegerField(default=0, help_text='Minute of the event in the match')),
                ('extra_time', models.PositiveIntegerField(blank=True, help_text='Extra time minute if applicable', null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_player', to='api.player')),
                ('substitute_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_player', to='api.player')),
                ('playMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.playmatch')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ManyToManyField(related_name='players', to='api.position'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('coach', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='team_logo/')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground', to='api.ground')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='api.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='api.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='api.team'),
        ),
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_scored', models.PositiveIntegerField(default=0)),
                ('goals_conceded', models.PositiveIntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'ordering': ['-points', '-goal_difference', '-goals_scored'],
                'unique_together': {('team', 'season')},
            },
        ),
    ]
