# Generated by Django 5.0.6 on 2024-07-02 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playmatch',
            name='fixture',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fixture', to='api.fixture'),
        ),
    ]
