# Generated by Django 5.0.6 on 2024-07-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_playmatch_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
