# Generated by Django 5.0.6 on 2024-07-03 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_leaguetable_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Transfer News', 'Transfer News'), ('Club News', 'Club News'), ('Match Reports', 'Match Reports'), ('Injury Updates', 'Injury Updates'), ('Training Updates', 'Training Updates'), ('Player Interviews', 'Player Interviews'), ('Manager Interviews', 'Manager Interviews'), ('Fan News', 'Fan News'), ('League Announcements', 'League Announcements')], max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('is_featured', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='news_videos/')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
