# Generated by Django 5.0.6 on 2024-07-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_news_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
