# Generated by Django 5.0.6 on 2024-07-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_playmatch_result_teamform'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
